// projects/vite/vite3-react-ssr/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'

interface IAppProps {
  data?: typeof window.__SSR_DATA__;
}

const App: React.FC<IAppProps> = (props) => {
  const { data } = props;
  const [count, setCount] = useState(0);

  return (
    <div className="App">
      <h5>hydrate数据</h5>
      <div>user: {data?.user} </div>
      <div>date: {data?.date} </div>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src="/vite.svg" className="logo" alt="Vite logo" />
        </a>
        <a href="https://reactjs.org" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </div>
  );
};

export default App

// projects/vite/vite-vue3/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
import Test from './components/Test.jsx'
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
  <Test></Test>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}

.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}

.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
